/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";
import ParentLayout from "@/layouts/parent-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
  parent: ParentLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "driver-check-in": () => import("@/views/_builtin/driver-check-in/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "social-callback": () => import("@/views/_builtin/social-callback/index.vue"),
  "user-center": () => import("@/views/_builtin/user-center/index.vue"),
  about: () => import("@/views/about/index.vue"),
  "basic_platform-warehouse": () => import("@/views/basic/platform-warehouse/index.vue"),
  demo_demo: () => import("@/views/demo/demo/index.vue"),
  demo_tree: () => import("@/views/demo/tree/index.vue"),
  home: () => import("@/views/home/index.vue"),
  monitor_cache: () => import("@/views/monitor/cache/index.vue"),
  monitor_logininfor: () => import("@/views/monitor/logininfor/index.vue"),
  monitor_online: () => import("@/views/monitor/online/index.vue"),
  monitor_operlog: () => import("@/views/monitor/operlog/index.vue"),
  system_client: () => import("@/views/system/client/index.vue"),
  system_config: () => import("@/views/system/config/index.vue"),
  system_dept: () => import("@/views/system/dept/index.vue"),
  system_dict: () => import("@/views/system/dict/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_notice: () => import("@/views/system/notice/index.vue"),
  "system_oss-config": () => import("@/views/system/oss-config/index.vue"),
  system_oss: () => import("@/views/system/oss/index.vue"),
  system_post: () => import("@/views/system/post/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  "system_tenant-package": () => import("@/views/system/tenant-package/index.vue"),
  system_tenant: () => import("@/views/system/tenant/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  tool_gen: () => import("@/views/tool/gen/index.vue"),
  "wms_devanning-order": () => import("@/views/wms/devanning-order/index.vue"),
  wms_inventory_location: () => import("@/views/wms/inventory/location/index.vue"),
  "wms_inventory_warehouse-area": () => import("@/views/wms/inventory/warehouse-area/index.vue"),
  "wms_order_cargo-inbound-plan": () => import("@/views/wms/order/cargo-inbound-plan/index.vue"),
  "wms_order_devanning-order": () => import("@/views/wms/order/devanning-order/index.vue"),
  "wms_order_driver-check-in-record": () => import("@/views/wms/order/driver-check-in-record/index.vue"),
  "wms_order_import-inventory": () => import("@/views/wms/order/import-inventory/index.vue"),
  "wms_order_inventory-data-dashboard": () => import("@/views/wms/order/inventory-data-dashboard/index.vue"),
  "wms_order_inventory-data": () => import("@/views/wms/order/inventory-data/index.vue"),
  "wms_order_outstock-data": () => import("@/views/wms/order/outstock-data/index.vue"),
  "wms_order_outstock-exception": () => import("@/views/wms/order/outstock-exception/index.vue"),
  "wms_order_park-management": () => import("@/views/wms/order/park-management/index.vue"),
  "wms_order_park-scheduling": () => import("@/views/wms/order/park-scheduling/index.vue"),
  "wms_order_warehouse-inventory-map": () => import("@/views/wms/order/warehouse-inventory-map/index.vue"),
  wms_warehouse_settings_location: () => import("@/views/wms/warehouse/settings/location/index.vue"),
  "wms_warehouse_settings_prelocation-exception-log": () => import("@/views/wms/warehouse/settings/prelocation-exception-log/index.vue"),
  "wms_warehouse_settings_putaway-config": () => import("@/views/wms/warehouse/settings/putaway-config/index.vue"),
  "wms_warehouse_settings_warehouse-area": () => import("@/views/wms/warehouse/settings/warehouse-area/index.vue"),
};
