/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 99
    }
  },
  {
    name: 'basic',
    path: '/basic',
    component: 'layout.base',
    meta: {
      title: 'basic',
      i18nKey: 'route.basic',
      icon: 'material-symbols:database-outline',
      order: 2
    },
    children: [
      {
        name: 'basic_platform-warehouse',
        path: '/basic/platform-warehouse',
        component: 'view.basic_platform-warehouse',
        meta: {
          title: 'basic_platform-warehouse',
          i18nKey: 'route.basic_platform-warehouse',
          icon: 'material-symbols:warehouse-outline'
        }
      }
    ]
  },
  {
    name: 'demo',
    path: '/demo',
    component: 'layout.base',
    meta: {
      title: 'demo',
      i18nKey: 'route.demo'
    },
    children: [
      {
        name: 'demo_demo',
        path: '/demo/demo',
        component: 'view.demo_demo',
        meta: {
          title: 'demo_demo',
          i18nKey: 'route.demo_demo'
        }
      },
      {
        name: 'demo_tree',
        path: '/demo/tree',
        component: 'view.demo_tree',
        meta: {
          title: 'demo_tree',
          i18nKey: 'route.demo_tree'
        }
      }
    ]
  },
  {
    name: 'driver-check-in',
    path: '/driver-check-in',
    component: 'layout.blank$view.driver-check-in',
    meta: {
      title: 'driver-check-in',
      i18nKey: 'route.driver-check-in',
      constant: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_cache',
        path: '/monitor/cache',
        component: 'view.monitor_cache',
        meta: {
          title: 'monitor_cache',
          i18nKey: 'route.monitor_cache'
        }
      },
      {
        name: 'monitor_logininfor',
        path: '/monitor/logininfor',
        component: 'view.monitor_logininfor',
        meta: {
          title: 'monitor_logininfor',
          i18nKey: 'route.monitor_logininfor'
        }
      },
      {
        name: 'monitor_online',
        path: '/monitor/online',
        component: 'view.monitor_online',
        meta: {
          title: 'monitor_online',
          i18nKey: 'route.monitor_online'
        }
      },
      {
        name: 'monitor_operlog',
        path: '/monitor/operlog',
        component: 'view.monitor_operlog',
        meta: {
          title: 'monitor_operlog',
          i18nKey: 'route.monitor_operlog'
        }
      }
    ]
  },
  {
    name: 'social-callback',
    path: '/social-callback',
    component: 'layout.blank$view.social-callback',
    meta: {
      title: 'social-callback',
      i18nKey: 'route.social-callback',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      localIcon: 'menu-system',
      order: 1
    },
    children: [
      {
        name: 'system_client',
        path: '/system/client',
        component: 'view.system_client',
        meta: {
          title: 'system_client',
          i18nKey: 'route.system_client'
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          localIcon: 'menu-tree-table',
          order: 3
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice'
        }
      },
      {
        name: 'system_oss',
        path: '/system/oss',
        component: 'view.system_oss',
        meta: {
          title: 'system_oss',
          i18nKey: 'route.system_oss'
        }
      },
      {
        name: 'system_oss-config',
        path: '/system/oss-config',
        component: 'view.system_oss-config',
        meta: {
          title: 'system_oss-config',
          i18nKey: 'route.system_oss-config',
          constant: true,
          hideInMenu: true,
          icon: 'hugeicons:configuration-01'
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_tenant',
        path: '/system/tenant',
        component: 'view.system_tenant',
        meta: {
          title: 'system_tenant',
          i18nKey: 'route.system_tenant'
        }
      },
      {
        name: 'system_tenant-package',
        path: '/system/tenant-package',
        component: 'view.system_tenant-package',
        meta: {
          title: 'system_tenant-package',
          i18nKey: 'route.system_tenant-package'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'tool',
    path: '/tool',
    component: 'layout.base',
    meta: {
      title: 'tool',
      i18nKey: 'route.tool',
      localIcon: 'menu-tool',
      order: 4
    },
    children: [
      {
        name: 'tool_gen',
        path: '/tool/gen',
        component: 'view.tool_gen',
        meta: {
          title: 'tool_gen',
          i18nKey: 'route.tool_gen',
          localIcon: 'menu-code',
          order: 2
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      icon: 'material-symbols:account-circle-full',
      hideInMenu: true
    }
  },
  {
    name: 'wms',
    path: '/wms',
    component: 'layout.base',
    meta: {
      title: 'wms',
      i18nKey: 'route.wms',
      icon: 'mdi:warehouse',
      order: 5
    },
    children: [
      {
        name: 'wms_devanning-order',
        path: '/wms/devanning-order',
        component: 'view.wms_devanning-order',
        meta: {
          title: 'wms_devanning-order',
          i18nKey: 'route.wms_devanning-order',
          hideInMenu: true
        }
      },
      {
        name: 'wms_inventory',
        path: '/wms/inventory',
        meta: {
          title: 'wms_inventory',
          i18nKey: 'route.wms_inventory',
          icon: 'material-symbols:inventory-outline'
        },
        children: [
          {
            name: 'wms_inventory_location',
            path: '/wms/inventory/location',
            component: 'view.wms_inventory_location',
            meta: {
              title: 'wms_inventory_location',
              i18nKey: 'route.wms_inventory_location'
            }
          },
          {
            name: 'wms_inventory_warehouse-area',
            path: '/wms/inventory/warehouse-area',
            component: 'view.wms_inventory_warehouse-area',
            meta: {
              title: 'wms_inventory_warehouse-area',
              i18nKey: 'route.wms_inventory_warehouse-area',
              icon: 'material-symbols:map-outline'
            }
          }
        ]
      },
      {
        name: 'wms_order',
        path: '/wms/order',
        meta: {
          title: 'wms_order',
          i18nKey: 'route.wms_order'
        },
        children: [
          {
            name: 'wms_order_cargo-inbound-plan',
            path: '/wms/order/cargo-inbound-plan',
            component: 'view.wms_order_cargo-inbound-plan',
            meta: {
              title: 'wms_order_cargo-inbound-plan',
              i18nKey: 'route.wms_order_cargo-inbound-plan'
            }
          },
          {
            name: 'wms_order_devanning-order',
            path: '/wms/order/devanning-order',
            component: 'view.wms_order_devanning-order',
            meta: {
              title: 'wms_order_devanning-order',
              i18nKey: 'route.wms_order_devanning-order'
            }
          },
          {
            name: 'wms_order_driver-check-in-record',
            path: '/wms/order/driver-check-in-record',
            component: 'view.wms_order_driver-check-in-record',
            meta: {
              title: 'wms_order_driver-check-in-record',
              i18nKey: 'route.wms_order_driver-check-in-record'
            }
          },
          {
            name: 'wms_order_import-inventory',
            path: '/wms/order/import-inventory',
            component: 'view.wms_order_import-inventory',
            meta: {
              title: 'wms_order_import-inventory',
              i18nKey: 'route.wms_order_import-inventory'
            }
          },
          {
            name: 'wms_order_inventory-data',
            path: '/wms/order/inventory-data',
            component: 'view.wms_order_inventory-data',
            meta: {
              title: 'wms_order_inventory-data',
              i18nKey: 'route.wms_order_inventory-data'
            }
          },
          {
            name: 'wms_order_inventory-data-dashboard',
            path: '/wms/order/inventory-data-dashboard',
            component: 'view.wms_order_inventory-data-dashboard',
            meta: {
              title: 'wms_order_inventory-data-dashboard',
              i18nKey: 'route.wms_order_inventory-data-dashboard'
            }
          },
          {
            name: 'wms_order_outstock-data',
            path: '/wms/order/outstock-data',
            component: 'view.wms_order_outstock-data',
            meta: {
              title: 'wms_order_outstock-data',
              i18nKey: 'route.wms_order_outstock-data'
            }
          },
          {
            name: 'wms_order_outstock-exception',
            path: '/wms/order/outstock-exception',
            component: 'view.wms_order_outstock-exception',
            meta: {
              title: 'wms_order_outstock-exception',
              i18nKey: 'route.wms_order_outstock-exception'
            }
          },
          {
            name: 'wms_order_park-management',
            path: '/wms/order/park-management',
            component: 'view.wms_order_park-management',
            meta: {
              title: 'wms_order_park-management',
              i18nKey: 'route.wms_order_park-management',
              icon: 'material-symbols:settings-outline'
            }
          },
          {
            name: 'wms_order_park-scheduling',
            path: '/wms/order/park-scheduling',
            component: 'view.wms_order_park-scheduling',
            meta: {
              title: 'wms_order_park-scheduling',
              i18nKey: 'route.wms_order_park-scheduling',
              icon: 'material-symbols:view-week-outline'
            }
          },
          {
            name: 'wms_order_warehouse-inventory-map',
            path: '/wms/order/warehouse-inventory-map',
            component: 'view.wms_order_warehouse-inventory-map',
            meta: {
              title: 'wms_order_warehouse-inventory-map',
              i18nKey: 'route.wms_order_warehouse-inventory-map'
            }
          }
        ]
      },
      {
        name: 'wms_warehouse',
        path: '/wms/warehouse',
        meta: {
          title: 'wms_warehouse',
          i18nKey: 'route.wms_warehouse'
        },
        children: [
          {
            name: 'wms_warehouse_settings',
            path: '/wms/warehouse/settings',
            meta: {
              title: 'wms_warehouse_settings',
              i18nKey: 'route.wms_warehouse_settings'
            },
            children: [
              {
                name: 'wms_warehouse_settings_location',
                path: '/wms/warehouse/settings/location',
                component: 'view.wms_warehouse_settings_location',
                meta: {
                  title: 'wms_warehouse_settings_location',
                  i18nKey: 'route.wms_warehouse_settings_location'
                }
              },
              {
                name: 'wms_warehouse_settings_prelocation-exception-log',
                path: '/wms/warehouse/settings/prelocation-exception-log',
                component: 'view.wms_warehouse_settings_prelocation-exception-log',
                meta: {
                  title: 'wms_warehouse_settings_prelocation-exception-log',
                  i18nKey: 'route.wms_warehouse_settings_prelocation-exception-log'
                }
              },
              {
                name: 'wms_warehouse_settings_putaway-config',
                path: '/wms/warehouse/settings/putaway-config',
                component: 'view.wms_warehouse_settings_putaway-config',
                meta: {
                  title: 'wms_warehouse_settings_putaway-config',
                  i18nKey: 'route.wms_warehouse_settings_putaway-config'
                }
              },
              {
                name: 'wms_warehouse_settings_warehouse-area',
                path: '/wms/warehouse/settings/warehouse-area',
                component: 'view.wms_warehouse_settings_warehouse-area',
                meta: {
                  title: 'wms_warehouse_settings_warehouse-area',
                  i18nKey: 'route.wms_warehouse_settings_warehouse-area'
                }
              }
            ]
          }
        ]
      }
    ]
  }
];
